### ISSUE TITLE
insufficient pipe handling

### ISSUE THREAD

**Issue by dosuser** [dosuser/word-frequency#1]
$ word-frequency -i t.bat  | more
bash: more: command not found
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: EPIPE: broken pipe, write
    at Socket._write (internal/net.js:58:25)
    at doWrite (_stream_writable.js:410:12)
    at writeOrBuffer (_stream_writable.js:394:5)
    at Socket.Writable.write (_stream_writable.js:294:11)
    at write (C:\Users\CA\AppData\Roaming\npm\node_modules\text-word-frequency\dum.js:48:15)
    at flushToSteam (C:\Users\CA\AppData\Roaming\npm\node_modules\text-word-frequency\dum.js:92:5)
    at C:\Users\CA\AppData\Roaming\npm\node_modules\text-word-frequency\dum.js:38:9
    at Interface.<anonymous> (C:\Users\CA\AppData\Roaming\npm\node_modules\text-word-frequency\dum.js:112:5)
    at Interface.emit (events.js:187:15)
    at Interface.close (readline.js:379:8)
Emitted 'error' event at:
    at onwriteError (_stream_writable.js:425:12)
    at onwrite (_stream_writable.js:456:5)
    at Socket._write (internal/net.js:62:14)
    at doWrite (_stream_writable.js:410:12)
    [... lines matching original stack trace ...]
    at Interface.<anonymous> (C:\Users\CA\AppData\Roaming\npm\node_modules\text-word-frequency\dum.js:112:5)

**Comment by dosuser** [comment]
solved
